-- MySQL Script generated by MySQL Workbench
-- Tue Nov  2 16:41:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ClickAr
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ClickAr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ClickAr` DEFAULT CHARACTER SET utf8 ;
USE `ClickAr` ;

-- -----------------------------------------------------
-- Table `ClickAr`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClickAr`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Mail` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Tipo_Documento` VARCHAR(45) NOT NULL,
  `Numero_Documento` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `mail_UNIQUE` (`Mail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClickAr`.`Destinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClickAr`.`Destinos` (
  `Codigo_Postal` INT NOT NULL,
  `Localidad` VARCHAR(45) NOT NULL,
  `Provincia` VARCHAR(45) NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`Codigo_Postal`),
  UNIQUE INDEX `idDestinos_UNIQUE` (`Codigo_Postal` ASC) VISIBLE,
  INDEX `idUsuario_idx` (`idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `FK_idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `ClickAr`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClickAr`.`Cupon_Descuento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClickAr`.`Cupon_Descuento` (
  `idCupon` INT NOT NULL AUTO_INCREMENT,
  `Detalle` VARCHAR(45) NOT NULL,
  `Descuento_Fijo` INT NOT NULL,
  `Codigo_Postal` INT NOT NULL,
  PRIMARY KEY (`idCupon`),
  UNIQUE INDEX `idCupon_UNIQUE` (`idCupon` ASC) VISIBLE,
  INDEX `Codigo_Postal_idx` (`Codigo_Postal` ASC) VISIBLE,
  CONSTRAINT `Codigo_Postal`
    FOREIGN KEY (`Codigo_Postal`)
    REFERENCES `ClickAr`.`Destinos` (`Codigo_Postal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClickAr`.`Restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClickAr`.`Restaurante` (
  `idRestaurante` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Localidad` VARCHAR(45) NOT NULL,
  `Provincia` VARCHAR(45) NOT NULL,
  `idCupon` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  UNIQUE INDEX `idRestaurante_UNIQUE` (`idRestaurante` ASC) VISIBLE,
  PRIMARY KEY (`idRestaurante`),
  UNIQUE INDEX `idCupon_UNIQUE` (`idCupon` ASC) VISIBLE,
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `idCupon`
    FOREIGN KEY (`idCupon`)
    REFERENCES `ClickAr`.`Cupon_Descuento` (`idCupon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `ClickAr`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
