-- MySQL Script generated by MySQL Workbench
-- Sun Nov 21 17:21:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema IEFI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IEFI` DEFAULT CHARACTER SET utf8 ;
USE `IEFI` ;

-- -----------------------------------------------------
-- Table `IEFI`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IEFI`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC));


-- -----------------------------------------------------
-- Table `IEFI`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IEFI`.`login` (
  `idLogin` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idLogin`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC),
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `IEFI`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `IEFI`.`destinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IEFI`.`destinos` (
  `codigo_postal` INT NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`codigo_postal`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC),
  CONSTRAINT `idUsuarioo`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `IEFI`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `IEFI`.`restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IEFI`.`restaurante` (
  `idRestaurante` INT NOT NULL,
  `nombre_restaurante` VARCHAR(45) NOT NULL,
  `codigo_postal` INT NOT NULL,
  PRIMARY KEY (`idRestaurante`),
  UNIQUE INDEX `idRestaurante_UNIQUE` (`idRestaurante` ASC),
  INDEX `codigo_postal_idx` (`codigo_postal` ASC),
  CONSTRAINT `codigo_postal`
    FOREIGN KEY (`codigo_postal`)
    REFERENCES `IEFI`.`destinos` (`codigo_postal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `IEFI`.`cupon_descuento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IEFI`.`cupon_descuento` (
  `idCupon` INT NOT NULL,
  `detalle` VARCHAR(45) NOT NULL,
  `idRestaurante` INT NOT NULL,
  PRIMARY KEY (`idCupon`),
  UNIQUE INDEX `idRestaurante_UNIQUE` (`idRestaurante` ASC),
  CONSTRAINT `idRestaurante`
    FOREIGN KEY (`idRestaurante`)
    REFERENCES `IEFI`.`restaurante` (`idRestaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
